services:
  parser-backend:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: parser-backend:jvm
    container_name: parser-backend
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS_APPEND: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
    restart: unless-stopped
